CREATE TABLE CAMPANA(
	ID_CAMPANA	NUMBER PRIMARY KEY,
	NOMBRE_CAMPANA VARCHAR2(1000),
	FECHA_INICIO DATE,
	FECHA_FIN	DATE
);

CREATE TABLE AREA(
	ID_AREA			NUMBER PRIMARY KEY,
	NOMBRE_AREA 	VARCHAR2(1000),
	ID_CAMPANA		NUMBER,
	 CONSTRAINT FK_AREA_CAMP
		FOREIGN KEY (ID_CAMPANA)
		REFERENCES CAMPANA(ID_CAMPANA)
);

CREATE TABLE PUESTO(
	ID_PUESTO		NUMBER PRIMARY KEY,
	NOMBRE_PUESTO 	VARCHAR2(1000),
	ID_AREA			NUMBER,
	 CONSTRAINT FK_PUEST_AREA
		FOREIGN KEY (ID_AREA)
		REFERENCES AREA(ID_AREA)
);

CREATE TABLE RESPONSABLE(
	ID_RESPONSABLE		NUMBER PRIMARY KEY,
	NOMBRE_RESPONSABLE 	VARCHAR2(1000),
	ID_PUESTO			NUMBER,
	 CONSTRAINT FK_PUEST_RESPO
		FOREIGN KEY (ID_PUESTO)
		REFERENCES PUESTO(ID_PUESTO)
);





CREATE TABLE CANDIDATO(
	ID_CANDIDATO		NUMBER PRIMARY KEY,
	NOMBRE_CANDIDATO 	VARCHAR2(1000),
	ID_CAMPANA 	NUMBER,
	 CONSTRAINT FK_CAND_CAMP
		FOREIGN KEY (ID_CAMPANA)
		REFERENCES CAMPANA(ID_CAMPANA)
);

CREATE TABLE VOTANTE(
	ID_VOTANTE		NUMBER PRIMARY KEY,
	NOMBRE_VOTANTE 	VARCHAR2(1000),
	CEDULA_VOTANTE 	VARCHAR2(1000),
	ID_CAMPANA		NUMBER,
	 CONSTRAINT FK_VOTA_CAMP
		FOREIGN KEY (ID_CAMPANA)
		REFERENCES CAMPANA(ID_CAMPANA)
	
);

CREATE TABLE DETALLE_VOTO(
	ID_VOTO		NUMBER PRIMARY KEY,
	ID_CANDIDATO 	NUMBER,
	ID_PUESTO 	NUMBER,
	 CONSTRAINT FK_VOTO_VOTAN
		FOREIGN KEY (ID_CANDIDATO)
		REFERENCES CANDIDATO(ID_CANDIDATO),
		
	 CONSTRAINT FK_VOTO_PUET
		FOREIGN KEY (ID_PUESTO)
		REFERENCES PUESTO(ID_PUESTO)
		
);